//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopWeeabo2.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopWeeabo2.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &apos;anime_entries&apos; (
        ///	&apos;id&apos; integer not null primary key,
        ///	&apos;id_mal&apos; integer,
        ///	&apos;average_score&apos; integer,
        ///	&apos;episodes&apos; integer,
        ///	&apos;duration&apos; integer,
        ///	&apos;type&apos; integer,
        ///	&apos;format&apos; integer,
        ///	&apos;status&apos; integer,
        ///	&apos;description&apos; string,
        ///	&apos;genres&apos; string,
        ///	&apos;synonyms&apos; string,
        ///	&apos;title_english&apos; string,
        ///	&apos;title_romaji&apos; string,
        ///	&apos;title_native&apos; string,
        ///	&apos;start_date&apos; text,
        ///	&apos;end_date&apos; text,
        ///	&apos;cover_image&apos; string,
        ///	&apos;viewing_status&apos; string,
        ///	&apos;personal_score&apos; integer,
        ///	&apos;personal_review&apos; string,
        ///	&apos;watch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateAnimeTable {
            get {
                return ResourceManager.GetString("CreateAnimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &apos;manga_entries&apos; (
        ///	&apos;id&apos; integer not null primary key,
        ///	&apos;id_mal&apos; integer,
        ///	&apos;average_score&apos; integer,
        ///	&apos;volumes&apos; integer,
        ///	&apos;chapters&apos; integer,
        ///	&apos;type&apos; integer,
        ///	&apos;format&apos; integer,
        ///	&apos;status&apos; integer,
        ///	&apos;description&apos; string,
        ///	&apos;genres&apos; string,
        ///	&apos;synonyms&apos; string,
        ///	&apos;title_english&apos; string,
        ///	&apos;title_romaji&apos; string,
        ///	&apos;title_native&apos; string,
        ///	&apos;cover_image&apos; string,
        ///	&apos;reading_status&apos; string,
        ///	&apos;personal_score&apos; integer,
        ///	&apos;personal_review&apos; string,
        ///	&apos;read_priority&apos; integer,
        ///	&apos;reread_count&apos; integ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateMangaTable {
            get {
                return ResourceManager.GetString("CreateMangaTable", resourceCulture);
            }
        }
    }
}
